### ISSUE TITLE
Chapter 2:  Failed to import cert file client.pem.crt, last error is 0x80092002

### ISSUE THREAD

**Issue by techtoys** [sborsay/AWS-Serverless-IoT-Book#2]
Hi Stephen

Following Chapter 2, certs and key were generated, name shortened, and copied to C:\Program Files\Git\mingw64\bin folder.

With `>dir *.crt`, `>dir *.key`, & `>dir *.pem`, I am able to confirm existance of those files as:
```
Directory of C:\Program Files\Git\mingw64\bin
21/10/2023  10:40 pm             1,220 client.pem.crt
21/10/2023  10:41 pm             1,675 private.pem.key
21/10/2023  10:43 pm             1,187 AmazonRootCA1.pem
```

From `C:\Program Files\Git\mingw64\bin>` the following command exec:

```
curl --tlsv1.2 ^
--cacert AmazonRootCA1.pem ^
--cert client.pem.crt ^
--key private.pem.key ^
--request POST ^
--data "{\"Temperature\": 77, \"Humidity\": 88, \"Time\": 12349876}" ^
"https://<My end-point>:8443/topics/outTopic?qos=1"
```

The following error message returned:
`curl: (58) schannel: Failed to import cert file client.pem.crt, last error is 0x80092002`

There is a problem with client.pem.crt certificate import, I think. How to solve it?

John

**Comment by sborsay** [comment]
So it is pretty common that different versions of cURL require different flags and arguments.  I just retired what you send me with my endpoint and certs and it worked fine.  This link may help with your version of cURL for troubleshooting.

https://github.com/sborsay/AWS-IoT/blob/master/AWSCurl_HTTPs_Payload_Tester

**Comment by techtoys** [comment]
Stephen

Key words in your post "different versions of cURL" is helping.

I found a solution:
1. Un-install Git-2.42.0.2-64-bit (with curl 8.2.1) which is the latest version at time of try-out.
2. Install an older version Git-2.24.1.2-64-bit [link](https://github.com/git-for-windows/git/releases/tag/v2.24.1.windows.2) (with curl 7.67.0)
3. Change names of the original certs and key to `private.pem.key` & ` certificate.pem.crt`  and using the same name in curl command below:

```
curl --tlsv1.2 ^
--cacert AmazonRootCA1.pem ^
--key private.pem.key ^
--cert certificate.pem.crt ^
--request POST ^
--data "{\"Temperature\": 77, \"Humidity\": 88, \"Time\": 12349876}" ^
"https://<my end point>:8443/topics/outTopic?qos=1"
```

Response:
`{"message":"OK","traceId":"cad83a13-cbee-cffc-30d5-07cc04fd9742"}`

Now my mqtt test client is receiving data.

Thanks a lot.

John

**Comment by sborsay** [comment]
here is an AWS coupon code for you

PCTAJYCGCWV83I

**Comment by techtoys** [comment]
Thanks a lot for the coupon.
